# Generated by Django 5.2.4 on 2025-07-08 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, max_length=255, null=True)),
                ('block_type', models.CharField(max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='BlockTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_zh', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.CharField(default='h2', max_length=255)),
                ('align', models.CharField(default='left', max_length=255)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='blocks.contentblock')),
            ],
        ),
        migrations.CreateModel(
            name='BlockText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_zh', models.TextField()),
                ('text_en', models.TextField(blank=True, null=True)),
                ('is_rich', models.BooleanField(default=False)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='blocks.contentblock')),
            ],
        ),
        migrations.CreateModel(
            name='BlockImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('caption_zh', models.CharField(blank=True, max_length=255, null=True)),
                ('caption_en', models.CharField(blank=True, max_length=255, null=True)),
                ('align', models.CharField(default='center', max_length=255)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blocks.contentblock')),
            ],
        ),
    ]
